# Generated by Django 3.0.6 on 2020-06-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0003_employeedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=255)),
                ('your_email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('form_completion', models.BooleanField(default=False)),
            ],
        ),
    ]
