# Generated by Django 3.0.6 on 2020-06-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0004_employerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reccomendation',
            field=models.CharField(default='No reccomendations yet!', max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='offer_letter',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='reccomendation',
            field=models.CharField(default='No reccomendations yet!', max_length=255),
        ),
    ]
