# Generated by Django 3.0.6 on 2020-06-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0005_auto_20200609_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employerdata',
            field=models.ManyToManyField(to='customUsers.EmployerData'),
        ),
    ]
