# Generated by Django 3.0.6 on 2020-06-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0006_employer_employerdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='employerdata',
        ),
        migrations.AddField(
            model_name='employer',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
