# Generated by Django 3.0.6 on 2020-06-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0007_auto_20200611_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employerdata',
            field=models.ManyToManyField(to='customUsers.EmployerData'),
        ),
    ]
