# Generated by Django 3.0.6 on 2020-06-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0008_employer_employerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company_name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager_email',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager_name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='offer_letter',
            field=models.FileField(default='null', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='recruiter_name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='recruiter_email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
