# Generated by Django 3.0.6 on 2020-06-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0009_auto_20200611_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='employerdata',
        ),
    ]
